import type { NextPage } from 'next'
import Head from 'next/head'

import { Editor } from '../src/editor'
import { Preview } from '../src/preview'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Editor />
        <Preview />
      </main>
    </>
  )
}

export default Home
